version: '3.9'

services:
  web:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:web_${IMAGE_TAG}
    build:
      context: ./app/web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - uwsgi-flask
    restart: always
  uwsgi-flask:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:flask_${IMAGE_TAG}
    build:
      context: ./app/flask
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    volumes:
      - "./app/flask:/app"
    restart: always
  frontend-admin:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:frontend_admin_${IMAGE_TAG}
    build:
      context: ./frontend-admin
      dockerfile: Dockerfile
      target: dev_builder