version: '3.9'

services:
  web:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:web_${IMAGE_TAG}
    build:
      context: ./app/web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - flask
    restart: always
  flask:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:flask_${IMAGE_TAG}
    build:
      context: ./app/flask
      dockerfile: Dockerfile
    expose:
      - 5000
    volumes:
      - "./app/flask:/app"
    restart: always
  frontend-admin:
    image: ${ECR_REGISTRY}/${ECR_FRONTEND_ADMIN_REPOSITORY}:${IMAGE_TAG}
    build:
      context: ./app/frontend-admin
      target: runner
    tty: true
    command: yarn build && yarn start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - ./app/frontend-admin:/app
