version: '3.9'

services:
  web:
    build:
      context: ./app/web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - flask
    restart: always
  flask:
    build:
      context: ./app/flask
      dockerfile: Dockerfile
    expose:
      - 5000
    volumes:
      - "./app/flask:/app"
    restart: always
    depends_on:
      - frontend-admin
  frontend-admin:
    build:
      context: ./app/frontend-admin
      target: runner
    tty: true
    command: yarn dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./app/frontend-admin:/app
